kumuluzee:
  name: rso1920-file-manager
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8089/
    http:
      port: 8089
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 30
    ping-interval: 5
  health:
    checks:
      etcd-health-check:
        connection-url: http://localhost:2379/health
  metrics:
    web-instrumentation:
      - name: catalog-endpoint
        url-pattern: /v1/file/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="comments">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="cfffe2f5-63d9-4c32-a175-636585889410-ls.logit.io"
                              port="21975" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'
rest-config:
  channel-uri: /v1/channels
  catalog-uri: /v1/fileMetadata

  upload-catalog-api-uri: /v1/fileMetadata
  upload-file-storage-api-uri: /v1/fileTransfer

  delete-catalog-api-uri: /v1/fileMetadata
  delete-file-storage-api-uri: /v1/fileTransfer