kumuluzee:
  name: rso-file-manager
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8089/
    http:
      port: 8089
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379

rest-config:
  upload-catalog-api-url: http://localhost:8088/v1/fileMetadata
  upload-file-storage-api-url: http://localhost:8080/v1/fileTransfer/storeFile

  delete-catalog-api-url: http://localhost:8088/v1/fileMetadata
  delete-file-storage-api-url: http://localhost:8080/v1/fileTransfer/storeFile