apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso1920-file-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso1920-file-manager
  template:
    metadata:
      labels:
        app: rso1920-file-manager
    spec:
      containers:
        - image: rso1920/filemanager:latest
          name: rso1920-file-manager
          env:
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://10.28.2.251:8089
            - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
              value: http://etcd:2379/health
          ports:
            - containerPort: 8089
              name: file-manager
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: file-manager
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: file-manager
            initialDelaySeconds: 60
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: rso1920-file-manager
spec:
  type: ClusterIP
  ports:
    - port: 8089
      protocol: TCP
      targetPort: file-manager
  selector:
    app: rso1920-file-manager
